language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mtalele/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mtalele/react-test npm test 

after_success:
  - docker build -t mtalele/multi-client ./client
  - docker build -t mtalele/multi-server ./server
  - docker build -t mtalele/multi-nginx ./nginx
  - docker build -t mtalele/multi-worker ./worker
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the images and push to docker hub 
  - docker push mtalele/multi-worker
  - docker push mtalele/multi-nginx
  - docker push mtalele/multi-server
  - docker push mtalele/multi-client 


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-973541247255
  bucket_path : docker-Multi
  on:
    branch : master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


