version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  # nginx is used for Routing to express server or react (client) 
  # as per the default.conf file. The routing are placed in this file.  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'  
  api: 
    build: 
       # dockerfile is just the name of the file
      dockerfile: Dockerfile.dev 
      # specify the folder in which the to build
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # This syntax sets the variable at the run time 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432  
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
